name: Atcoder-auto-commit-and-push

on:
  schedule: # execute every 24 hours
    - cron: "* */24 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git remote set-url origin https://github.com/${NAME}/${REPO}.git
          git add .
          git commit -m "add: solver"
          git pull
          git push origin main
        env:
          NAME: "ac2393921"
          REPO: "atcoder"
