name: Atcoder-auto-commit-and-push

on:
  schedule: # execute every 24 hours
    - cron: "* */24 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Check diff
        id: diff
        run: |
          git add -N .
          git diff --name-only --exit-code
        continue-on-error: true
      - name: Run commit and push
        run: |
          git config user.email $NAME
          git config user.name $EMAIL
          git remote set-url origin https://github.com/${NAME}/${REPO}.git
          git add .
          git commit -m "add: solver"
          git pull
          git push origin main
        env:
          NAME: "ac2393921"
          EMAIL: "ac2393921@gmail.com"
          REPO: "atcoder"
